FROM node:18

# Set the working directory
WORKDIR /app

# Copy only the package files first to leverage caching
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the application port
EXPOSE 3001

# Start the application
CMD ["npm", "run", "dock"]
