services:
  cpp-server:
    build: .
    container_name: cpp-app
    networks:
      - notflix-network
    ports:
      - "12345:12345" # Expose the C++ server port
    volumes:
      - ./src:/Notflix/src
      - ./tests:/Notflix/tests
    restart: always

  node-app:
    build: ./src/nodejs
    container_name: node-app
    depends_on:
      - mongo
      - cpp-server # Ensure the C++ server starts first
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=local
      - CONNECTION_STRING=mongodb://mongo:27017/Notflix
      - CPP_SERVER=cpp-app:12345
      - PORT=3001
    networks:
      - notflix-network
    volumes:
      - ./src/nodejs:/app
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - notflix-network

  react:
    build:
      context: ./src/react-frontend
      args:
      - REACT_APP_API_URL=http://localhost:3001/api
      - REACT_APP_MEDIA_URL=http://localhost:3001
    container_name: react-app
    depends_on:
      - node-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://localhost:3001/api
      - REACT_APP_MEDIA_URL=http://localhost:3001
    networks:
      - notflix-network
    restart: always

networks:
  notflix-network: # Shared network for all services
    driver: bridge

volumes:
  mongo-data:
